### ISSUE TITLE
dotnet core has limited task compared to dotnet? and can custom task work with other wexflow task as input/output?

### ISSUE THREAD

**Issue by zeusmos** [aelassas/Wexflow#109]
1. dotnet core has limited task compared to dotnet?

2. when a custom task is implement can it take input from other wexflow task and as well as send output to other wexflow task?

**Comment by aelassas** [comment]
@zeusmos Below are the answers to your questions:

1. Wexflow provides 100 built-in tasks for the .NET version and 66 built-in tasks for the .NET Core version. Every solution has its advantages. The .NET version provides more built-in tasks than the the .NET Core version and the .NET Core version provides some tasks that are available for .NET Core only such as YouTube tasks and Reddit tasks (coming soon in the v4.4). Moreover, the .NET Core version allow to launch GUI processes and display their GUI whereas in the .NET version it is not possible because Wexflow server is hosted in a Windows service.

2. State is transferred between tasks through selectFiles and through selectEntities settings. Check out the [documentation](https://github.com/aelassas/Wexflow/wiki/Usage#how-tasks-communicate-between-each-other).

**Comment by zeusmos** [comment]
> 
> 
> @zeusmos Below are the answers to your questions:
> 
>     1. Wexflow provides 100 built-in tasks for the .NET version and 66 built-in tasks for the .NET Core version. Every solution has its advantages. The .NET version provides more built-in tasks than the the .NET Core version and the .NET Core version provides some tasks that are available for .NET Core only such as YouTube tasks and Reddit tasks (coming soon in the v4.4). Moreover, the .NET Core version allow to launch GUI processes and display their GUI whereas in the .NET version it is not possible because Wexflow server is hosted in a Windows service.
> 

is it possible to use both version(.NET Core and .NET) to create workflows and have one version installed on server Dev to support both workflows created in (.NET Core and .NET) ?

**Comment by aelassas** [comment]
The architecture of the .NET version and the .NET Core version are different. It is not possible to create one version that support both .NET and .NET Core workflows.

**Comment by zeusmos** [comment]
Are there any option to run these both instance on same server instead of spinning up a new server for both versions? Or how can we manage both version on same server?

**Comment by aelassas** [comment]
You can install the two versions on the same server. You just have to change the port of the .NET Core version in Wexflow.Server\appsettings.json before to run it. The setting to change in the configuration file is WexflowServicePort. You will also have to change the port in the back end in the configuration file js\settings.js. The setting to change in the configuration file is Uri. You can have two back ends. One for the .NET version and one for the .NET Core version.

**Comment by zeusmos** [comment]
ok thanks
