### ISSUE TITLE
"Approval" tab not showing up in the Backend header bar

### ISSUE THREAD

**Issue by michaelstewartcopp** [aelassas/Wexflow#222]
Please let me know if there's something I need to configure (I'm able to process approvals via the Wexflow Manager app):

![image](https://user-images.githubusercontent.com/64225294/80140884-020d7a80-857f-11ea-93e8-33ad9bb95675.png)

**Comment by aelassas** [comment]
@michaelstewartcopp I removed Approval tab and added approval buttons in the manager tab. Just search for your approval workflows in the manager tab and you can approve/reject your approval workflows from the manager tab in the backend. I removed Approval tab because there was a lot of duplication between Approval and Manager tabs in the backend. Also, now there is parallel approval jobs support from the manager tab. Just start your approval workflow from the manager and then select the approval job from the jobs view in the manager and you can approve/reject the job.

**Comment by michaelstewartcopp** [comment]
Sounds good - thanks Akram
